ACTIVE_PROFILE: prod
PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: 192.168.68.102
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb
SERVER_PORT: 8080
UI_APP_URL: http://localhost:3000
USER_NAME: admin
USER_PASSWORD: letmein