spring:
  application:
    name: discoveryservice
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${MYSQL_DATABASE}
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${USER_NAME}:${USER_PASSWORD}@${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.33
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 3000
server:
  port: ${SERVER_PORT}