ACTIVE_PROFILE: prod
MYSQL_USERNAME: root
MYSQL_PASSWORD: J0hen314vs1
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: authorization
ROLES: EUREKA_CLIENT
SERVER_PORT: 5002
UI_APP_URL: http://localhost:3000
USER_NAME: admin
USER_PASSWORD: letmein